extensions:

receivers:
  loadgen:
  # Higher concurrency value translates to higher load
   concurrency: 1
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4318"
processors:
  transform/rewrite:  # Rewrite telemetry to increase cardinality
    trace_statements:
      - context: span
        statements:
          # The worst way to generate a random ID, but is the simplest in OTTL
          # Only randomize trace ID such that span relationships are still maintained
          - set(trace_id.string, Substring(MD5(UUID()), 0, 32))

exporters:
  debug:
  otlp/2:
    endpoint: 0.0.0.0:4318
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [loadgen]
      processors: [transform/rewrite]
      exporters: [debug]
    metrics:
      receivers: [loadgen]
      processors: [transform/rewrite]
      exporters: [debug]
    traces:
      receivers: [loadgen]
      processors: [transform/rewrite]
      exporters: [debug, otlp/2]
    traces/2:
      receivers: [otlp]
      processors: []
      exporters: [debug]
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
